/* THIS SCRIPT CREATES A VIEW CONTAINING SEARCH IDS EACH INDIVIDUAL WORD ON A QUERY AS ROWS */

USE DATABASE COV_INTERVIEW;

CREATE OR REPLACE VIEW public.keywords AS(

SELECT JSONTEXT:ID::VARCHAR id,VALUE FROM SEARCHES, lateral
         split_to_table(SEARCHES.JSONTEXT:QUERYEXPRESSION::VARCHAR,' ')
  );
